<a href="https://colab.research.google.com/github/KaitoAMANO/EU_M_Math/blob/main/Chap05_Ex_01_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
from pandas import Series, DataFrame
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns

sample_names = np.array(['a', 'b', 'c', 'd', 'a'])
random.seed(0)
data = random.randn(5, 5)

print(sample_names)
print(data)

print(data[sample_names == 'b'])

print(data[sample_names != 'c'])

x_array = np.array([1, 2, 3, 4, 5])
y_array = np.array([6, 7, 8, 9, 10])

cond_data = np.array([False, False, True, True, False])

print(np.where(cond_data, x_array, y_array))

sample_multi_array_data2 = np.arange(16).reshape(4, 4)

print(np.sqrt(sample_multi_array_data2))

print('最大値：', sample_multi_array_data2.max())
print('最小値：', sample_multi_array_data2.min())
print('合計値：', sample_multi_array_data2.sum())
print('平均値：', sample_multi_array_data2.mean())

print('対角成分の和：', np.trace(sample_multi_array_data2))

sample_array1, sample_array2 = np.arange(12).reshape(3, 4), np.arange(12).reshape(3, 4)

print(np.concatenate([sample_array1, sample_array2]))

print(np.concatenate([sample_array1, sample_array2], axis=1))

sample_list = [1, 2, 3, 4, 5]

print(np.array(sample_list) + 3)

['a' 'b' 'c' 'd' 'a']
[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799]
 [-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462]]
[[-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]]
[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799]
 [-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462]]
[ 6  7  3  4 10]
[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]
 [3.46410162 3.60555128 3.74165739 3.87298335]]
最大値： 15
最小値： 0
合計値： 120
平均値： 7.5
対角成分の和： 30
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0